### ISSUE TITLE
ModuleNotFoundError on fresh git install

### ISSUE THREAD

**Issue by noraj** [python-security/pyt#102]
Hi,

I just follow the install steps : 

```
$ git clone https://github.com/python-security/pyt.git
$ cd pyt/
# python setup.py install
$ pyt -h
```

But I get an error:

```
$ pyt -h
Traceback (most recent call last):
  File "/usr/bin/pyt", line 11, in <module>
    load_entry_point('python-taint==0.12', 'console_scripts', 'pyt')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/python_taint-0.12-py3.6.egg/pyt/__init__.py", line 1, in <module>
    from .__main__ import main
  File "/usr/lib/python3.6/site-packages/python_taint-0.12-py3.6.egg/pyt/__main__.py", line 24, in <module>
    from .formatters import (
ModuleNotFoundError: No module named 'pyt.formatters'
```

Of course my default python is 3.6:

```
python
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I'm under Manjaro.

**Comment by KevinHock** [comment]
This should be good now with https://github.com/python-security/pyt/pull/103  👍 Thanks again for reporting.

**Comment by noraj** [comment]
You're welcome, it's the pleasure to see the project is maintained. By the way I re-try the upstream git version and it's working now.
