### ISSUE TITLE
Trigger words does not exist

### ISSUE THREAD

**Issue by Ekultek** [python-security/pyt#122]
```
Traceback (most recent call last):
  File "/usr/local/bin/pyt", line 11, in <module>
    load_entry_point('python-taint==0.30', 'console_scripts', 'pyt')()
  File "/usr/local/lib/python3.6/site-packages/python_taint-0.30-py3.6.egg/pyt/__main__.py", line 307, in main
    args.trigger_word_file
  File "/usr/local/lib/python3.6/site-packages/python_taint-0.30-py3.6.egg/pyt/vulnerabilities.py", line 520, in find_vulnerabilities
    definitions = parse(vulnerability_files.triggers)
  File "/usr/local/lib/python3.6/site-packages/python_taint-0.30-py3.6.egg/pyt/trigger_definitions_parser.py", line 51, in parse
    with open(trigger_word_file, 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/python_taint-0.30-py3.6.egg/pyt/vulnerability_definitions/all_trigger_words.pyt'
```

Running context: `pyt -f <FILE>.py` or `python -m pyt -f <FILE>.py`

**Comment by KevinHock** [comment]
Fixed 😀 Thanks 👍

**Comment by KevinHock** [comment]
i thanked you in the changelog https://github.com/python-security/pyt/blob/master/CHANGELOG.md
