### ISSUE TITLE
SyntaxError: Non-ASCII character 

### ISSUE THREAD

**Issue by KevinHock** [python-security/pyt#22]
Due to https://github.com/python-security/pyt/blob/master/pyt/cfg.py#L21 we get 
```
Kevins-MacBook-Pro-2:example kevinhock$ python cfg_example.py 
Traceback (most recent call last):
  File "cfg_example.py", line 5, in <module>
    from cfg import CFG, print_CFG, generate_ast
  File "/Users/kevinhock/kpyt/pyt/pyt/cfg.py", line 21
SyntaxError: Non-ASCII character '\xc2' in file /Users/kevinhock/kpyt/pyt/pyt/cfg.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

which I think is fixed by adding
```python
# -*- coding: utf-8 -*-
```
to the top of cfg.py

But, I think it'd be better to just get a new CALL_IDENTIFIER, thoughts?

(Same holds for https://github.com/python-security/pyt/blob/master/pyt/base_cfg.py#L16)

**Comment by KevinHock** [comment]
(I realized it's a Python3 codebase :man_facepalming: )
