### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.../trigger_definitions/flask_trigger_words.pyt'

### ISSUE THREAD

**Issue by jwilk** [python-security/pyt#32]
I installed pyt using:
```console
$ python3 setup.py install --user
```
But apparently that didn't put the *.pyt files in the right place.
All I get is:
```console
$ pyt -f test.py
Traceback (most recent call last):
  File "/home/jwilk/.local/bin/pyt", line 11, in <module>
    load_entry_point('pyt==1.0.0a20', 'console_scripts', 'pyt')()
  File "/home/jwilk/.local/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/__main__.py", line 219, in main
    vulnerability_log = find_vulnerabilities(cfg_list, analysis)
  File "/home/jwilk/.local/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/vulnerabilities.py", line 291, in find_vulnerabilities
    definitions = parse(trigger_word_file)
  File "/home/jwilk/.local/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/trigger_definitions_parser.py", line 48, in parse
    with open(trigger_word_file, 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwilk/.local/lib/python3.5/site-packages/pyt-1.0.0a20-py3.5.egg/pyt/trigger_definitions/flask_trigger_words.pyt'
```
Tested with git master (96f6205808601a168582b49fbf9dfcb97ecd24f1).

**Comment by KevinHock** [comment]
Thanks for submitting this, I'll take a look soon.
